# Generated by Django 3.0.3 on 2020-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
