# Generated by Django 3.0.3 on 2021-05-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
