# Generated by Django 3.0.3 on 2021-05-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0003_auto_20210515_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
